"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(num: int) -> list[int]:
    fib = [1, 2]
    while fib[-1] <= num:
        fib.append(fib[-1] + fib[-2])
    return fib

def check_even(num: int) -> bool:
    if num % 2 == 0:
        return True
    return False

def even_fib_sum(num: int) -> int:
    fib = fibonacci(num)
    return sum([x for x in fib if check_even(x) == True])

print(even_fib_sum(4000000))
